# Generated by Django 3.1.12 on 2025-01-08 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20250108_2143'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='item',
        #     name='id',
        #     field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        # ),# Unsupported AlterField operation skipped for djongo compatibility.
    ]
