# Generated by Django 3.1.12 on 2025-01-10 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20250109_0148'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ValidBioID',
        ),
    ]
